[tool.black]
line-length = 88
target-version = ['py311']

[tool.ruff]
line-length = 88
select = ["E", "W", "F", "I", "C", "B"]
ignore = ["E501"] # Ignore line-too-long error, black handles this

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
